In [1]:
import numpy as np
import random

In [2]:
x = [1,2,3,4,5]

In [3]:
x

[1, 2, 3, 4, 5]

In [4]:
y = np.array(x)

In [5]:
print(x[0])
print(y[0])

1
1


In [6]:
print(x[::2])
print(y[::2])

[1, 3, 5]
[1 3 5]


In [7]:
y + y

array([ 2,  4,  6,  8, 10])

In [8]:
z = (1,2,3)
a = np.array(z)

print(z)
print(a)

(1, 2, 3)
[1 2 3]


In [9]:
x = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
y = np.array(x)

print(y[1][1])
print(y[1,1])

5
5


In [10]:
print(y[0:,[0,2]])
print(y[0:,1:2])

[[1 3]
 [4 6]
 [7 9]]
[[2]
 [5]
 [8]]


In [11]:
print(y[0:, :1]) # size = 3 shape=(3,1)
print('\n')
print(y[0:, :1].reshape(3,))
print('\n')
print(y[0:, 0].reshape(3,1)) # size = 3, shape=(3,)

[[1]
 [4]
 [7]]


[1 4 7]


[[1]
 [4]
 [7]]


In [17]:
y.ndim

2

In [13]:
c = [[[1,2,3], [4,5,6], [7,8,9]]]
c = np.array(c)
c.ndim

3

In [22]:
b = np.array([
    [4,5,6],
    [6,7,8],
    [8,9,0]
])

In [23]:
yb = y + b

In [24]:
yb

array([[ 5,  7,  9],
       [10, 12, 14],
       [15, 17,  9]])

In [25]:
yb.size

9

In [26]:
yb.dtype

dtype('int32')

In [27]:
yb.itemsize

4

In [28]:
yb.shape

(3, 3)

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [31]:
print(np.random.random(10))

[0.6949814  0.71648363 0.55006352 0.16717387 0.72506862 0.91425411
 0.2729954  0.25437564 0.81906033 0.27776899]


In [32]:
print(np.random.randint(10, size=10))

[1 8 0 5 6 0 4 7 5 4]


In [33]:
print(np.random.randint(10, size=(2,5)))

[[0 6 8 3 2]
 [9 7 4 9 2]]


In [34]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [35]:
np.linspace(0, 300, 11)

array([  0.,  30.,  60.,  90., 120., 150., 180., 210., 240., 270., 300.])

In [36]:
a = np.array([
    [0,-7],
    [-1,3]
])
b = np.array([
    [2,4],
    [3,8]
])

In [38]:
a+b

array([[ 2, -3],
       [ 2, 11]])

In [39]:
a-b

array([[ -2, -11],
       [ -4,  -5]])

In [40]:
a+2

array([[ 2, -5],
       [ 1,  5]])

In [41]:
a = np.array([
    [2,1],
    [1,1]
])
r = np.array([ 5, 7 ])
xy = np.linalg.solve(a,r)
print(xy)

[-2.  9.]


In [42]:
a = np.array([[3]])
r = np.array([6])
x = np.linalg.solve(a,r)
x

array([2.])

In [44]:
soal1 = np.array([
    [4,7],
    [3,2]
])
soal2 = np.array([
    2, -5
])

jawab = np.linalg.solve(soal1, soal2)
jawab

array([-3.,  2.])

In [45]:
x = jawab[0]
y = jawab[1]
jawaban=(2*x)-(3*y)
jawaban

-12.0

In [46]:
soal1 = np.array([
    [1,1],
    [2,4]
])
soal2 = np.array([
    25,70
])
jawaban = np.linalg.solve(soal1, soal2)
jawaban

array([15., 10.])

In [48]:
soal1 = np.array([
    [2,1,1],
    [1,2,1],
    [3,2,1]
])
soal2 = np.array([
    4700,4300,7100
])
jawaban = np.linalg.solve(soal1, soal2)
print(f'Harga 1 buku adalah {round(jawaban[0])}. Harga 1 pensil adalah {round(jawaban[1],1)}. Harga 1 penghapus adalah {round(jawaban[2],1)}')

Harga 1 buku adalah 1400.0. Harga 1 pensil adalah 1000.0. Harga 1 penghapus adalah 900.0


In [50]:
import functools
def maks_mins(a_list):
    x = np.array(a_list)
    x = np.sort(x)
    maks = x[-1]
    mins = x[0]
    sums = functools.reduce(lambda a,b: a+b, x)
    return(maks, mins, sums)

a_list=[1,3,5,6,4,2,3,5,7]
print(maks_mins(a_list))

(7, 1, 36)


In [51]:
x = np.array([1,2,3,4,5])
x = np.sort(x)
x

array([1, 2, 3, 4, 5])

In [52]:
x = [[1,20,3,400,5], [3,5,7,9,11]]
y = np.array(x)

print(y)
print(y.max())
print(y.min())
print(y.argmax())
print(y.argmin())
print(y.reshape(-1))
print(y.reshape(2,-1))
# print(y.reshape(2,5))

[[  1  20   3 400   5]
 [  3   5   7   9  11]]
400
1
3
0
[  1  20   3 400   5   3   5   7   9  11]
[[  1  20   3 400   5]
 [  3   5   7   9  11]]


In [53]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[0,0,0], [0,0,0]])
print(a+b)

[[1 2 3]
 [4 5 6]]


In [54]:
# vector identitas penjumlahan dan pengurangan
c = np.zeros((2,3), dtype='int32')
print(c)

[[0 0 0]
 [0 0 0]]


In [55]:
d = np.ones((2,3), dtype='int32')
d

array([[1, 1, 1],
       [1, 1, 1]])

In [56]:
x = np.zeros((3,3), dtype=bool)
print(x)

x = np.ones((3,3), dtype=bool)
print(x)

lain = np.full((3,3), 'Andi')
print(lain)

[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[['Andi' 'Andi' 'Andi']
 ['Andi' 'Andi' 'Andi']
 ['Andi' 'Andi' 'Andi']]


In [57]:
lain = np.full((3,3), 'Andi')
print(lain)
lain_list = lain.tolist()
print(lain_list)
print(type(lain_list))

[['Andi' 'Andi' 'Andi']
 ['Andi' 'Andi' 'Andi']
 ['Andi' 'Andi' 'Andi']]
[['Andi', 'Andi', 'Andi'], ['Andi', 'Andi', 'Andi'], ['Andi', 'Andi', 'Andi']]
<class 'list'>


In [58]:
x = [0,1,2,3,4]
y = [5,6,7,8,9]
# how to make z = [[0,1,2,3,4], [5,6,7,8,9]]

print('cara 1')
z = []
z.append(x)
z.append(y)
print(z)

print('cara 2')
z = [x, y]
print(z)

print('cara 3')
z = np.array(x+y).reshape(2,-1).tolist()
print(z)

print('cara 4')
a = []
a.extend(x)
a.extend(y)
z = np.array(a).reshape(2,-1).tolist()
print(z)

print('cara 5')
xnp = np.array(x)
ynp = np.array(y)
z = np.concatenate([[xnp],[ynp]], axis=0).tolist()
print(z)

print('cara 6')
z = np.vstack([xnp, ynp]).tolist()
print(z)

cara 1
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
cara 2
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
cara 3
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
cara 4
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
cara 5
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
cara 6
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]


In [59]:
a = np.arange(6).reshape(2,-1)
b = np.array([5,6,7,8,9,10]).reshape(2,-1)
d = np.concatenate([a,b], axis=0)
e = np.row_stack((a,b))
f = np.r_[a,b]

print(d)
print(e)
print(f)

[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]
[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]
[[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]


In [60]:
npa = np.arange(1,11)
print(npa)

#mengubah angka ganjil jadi 0
npa[npa%2!=0] = 0
print(npa)

[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  0  4  0  6  0  8  0 10]


In [61]:
x = np.arange(10,20)
print(np.where(x<16)) # menampilkan index value di bawah 16
print(x[np.where(x<16)]) # menampilkan value yang kurang dari 16
print(x[np.arange(5)]) # menampilkan value pada index 0-4 (arange(5))
print(x[np.where((x>14)&(x<18))]) # and operation using ampersand
print(x[np.logical_and(x>14, x<18)]) # and operation using logical_and fun

(array([0, 1, 2, 3, 4, 5], dtype=int64),)
[10 11 12 13 14 15]
[10 11 12 13 14]
[15 16 17]
[15 16 17]


In [62]:
a = np.array([
    [1,2,1],
    [3,3,1],
    [2,1,2]
])
print(np.linalg.det(a))

-6.0


In [63]:
z = np.array([[3,2], [1,4]])
print(np.linalg.inv(z))

# dot product
print(z@np.linalg.inv(z))
print(z.dot(np.linalg.inv(z)))

[[ 0.4 -0.2]
 [-0.1  0.3]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [64]:
def bigsum(ar):
    a = []
    base = 1000000000
    for i in range(ar):
        base += 1
        a.append(base)
    print(sum(a))

print(type(bigsum(5)))

5000000015
<class 'NoneType'>


In [65]:
ar = '1000000001 1000000002 1000000003 1000000004 1000000005'
ar_split = ar.split(' ')
new_list = []
for a in ar_split:
    new_list.append(int(a))
sum(new_list)

5000000015

In [66]:
z = [[9,10,2],
     [5,1,4],
    [3,5,6]]
z = np.array(z)
np.sort(z)

array([[ 2,  9, 10],
       [ 1,  4,  5],
       [ 3,  5,  6]])

In [67]:
np.sort(z, axis=0)

array([[ 3,  1,  2],
       [ 5,  5,  4],
       [ 9, 10,  6]])

In [68]:
np.sort(z, axis=1)

array([[ 2,  9, 10],
       [ 1,  4,  5],
       [ 3,  5,  6]])

In [69]:
np.sort(z, axis=None)

array([ 1,  2,  3,  4,  5,  5,  6,  9, 10])

In [70]:
x = np.arange(1,10).reshape(3,-1)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
print(x[:, [1,0,2]])
print('\n')
print(x[:, [0,0,0]])
print('\n')
print(x[[1,0,2],:])
print('\n')

[[2 1 3]
 [5 4 6]
 [8 7 9]]


[[1 1 1]
 [4 4 4]
 [7 7 7]]


[[4 5 6]
 [1 2 3]
 [7 8 9]]




In [72]:
a = np.array([[1,2], [3,4], [5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [73]:
print(a.transpose())

[[1 3 5]
 [2 4 6]]


In [81]:
x = np.loadtxt('test.csv', skiprows=1, delimiter=',')
print(x)

ValueError: could not convert string to float: 

In [77]:
id, usia = np.loadtxt('test.csv', skiprows=1, delimiter=',',unpack=True)
print(id)
print(usia)

OSError: test.csv not found.

In [78]:
c = np.vstack([id,usia]).transpose()
c

NameError: name 'usia' is not defined

In [79]:
np.savetxt('save_from_test.csv', c, fmt='%d',
           header='id,usia', delimiter=',', comments='')